[package]
name = "toasty-libsql"
version = "0.1.0"
edition = "2021"

[dependencies]
libsql = { path = "../libsql/libsql" }
toasty-core = { path = "../toasty/src/core/" }

# TODO: get rid of
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
anyhow = "1"
